name: vanillaEconomy
author: Psycofeu
api: 5.0.0
version: 1.0.0
description: https://discord.gg/vanillaMCBE

website: "https://github.com/Psycofeu"
main: psycofeu\vanillaEconomy\Main

permissions:
  givemoney.use:
    default: op
  takemoney.use:
    default: op
  setmoney.use:
    default: op